import Head from "next/head";
import PostArea from "../public/shared/PostArea";
import Right from "../public/shared/Right";
import Sidebar from "../public/shared/Sidebar";
import Story from "../public/shared/Story";

export default function Home() {
    return (
        <>
            <Head>
                <title>Instagram - Clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex justify-between">
                <div className="">
                    <Sidebar />
                </div>
                <div className="w-full h-screen">
                    <div className="w-full h-full flex flex-col overflow-auto scrollbar-hide">
                        <div className="h-[117px]">
                            <Story />
                        </div>
                        <PostArea />
                    </div>
                </div>
                <div className="hidden lg:flex justify-center">
                    <Right />
                </div>
            </div>
        </>
    );
}


